name: pr-push

on: 
  workflows: ["pr-required-labels"]
    types: 
      - completed
  
concurrency: 
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  clean-labels:
    runs-on: ubuntu-latest
    steps:
     - uses: actions-ecosystem/action-remove-labels@v1
       with:
        labels: 'safe to test'
